http:
  addr: ":8080"
  readTimeout: 15s
  writeTimeout: 30s
  idleTimeout: 60s

logging:
  env: "dev"
  service: "api-gateway"
  version: "0.1.0"
  backend: "zap"
  addSource: true
  debug: true

upstream:
  authTarget: "localhost:50051"
  roomGRPCTarget: "localhost:9092"